---

- name: create s3 bucket
  hosts: localhost
  connection: local
  vars_files:
  - cred.yml
  tasks:
  - name: create a simple bucket
     amazon.aws.s3_bucket:
        name: arun-ansible-buckets3-18april2023
        state: present
        region: ap-south-1
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
ubuntu@ip-172-31-42-247:~$ rm -rf s3_bucket.yml
ubuntu@ip-172-31-42-247:~$ cat new-sr_bucket.yml
---
- name: create s3 bucket
  hosts: localhost
  connection: local
  vars_files:
    - creds.yml
  tasks:
  - name: create a simple s3 bucket
    amazon.aws.s3_bucket:
      name: arun-ansible-buckets3
      state: present
      region: ap-south-1
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
